### PR TITLE
Fix plugin metrics not being sent

### LINKED ISSUE #59: Sending plugin metrics does not work in v1.3.0
The functionality described in https://github.com/SumoLogic/logstash-output-sumologic#monitor-throughput-in-metrics stopped working in v1.3.0. The `stats_enabled` flag is set to `true` but there are no plugin metrics coming in.

### PR DESCRIPTION
**Pull request by astencel-sumo**
Fixes #59.

This fix does not resolve the issue that the metrics `total_input_events` and `total_input_bytes` are not being calculated. This will be fixed separately.

### CODE REVIEW

File: lib/logstash/outputs/sumologic/sender.rb [hunk 1]
```diff
@@ -102,8 +102,6 @@ def send_request(batch)
 
       if @stats_enabled && content.start_with?(STATS_TAG)
         body = @compressor.compress(content[STATS_TAG.length..-1])
-        headers[CATEGORY_HEADER] = "#{headers[CATEGORY_HEADER]}.stats"
```
Comment (frankreno) [inline lib/logstash/outputs/sumologic/sender.rb:105]: Rather than appending `.stats` to the category.  Can we have a separate property for this? this could be fine from a default perspective but we should always give customers full control over the source category and not force customers into hardcoded values.

Comment (frankreno) [reply lib/logstash/outputs/sumologic/sender.rb:105]: If this is already the current behavior and not a new one we introduce, I am ok with leaving as is and adding better support in future release.

Comment (astencel-sumo) [reply lib/logstash/outputs/sumologic/sender.rb:105]: This is a quick & dirty kind of fix. We need to rethink defining of plugin metrics category, as the previous approach of appending ".stats" to payload source category will not work with templatized source category, like `%{field}`.

Comment (frankreno) [reply lib/logstash/outputs/sumologic/sender.rb:105]: Makes sense, ok we can track that in a separate issue then.

Comment (astencel-sumo) [reply lib/logstash/outputs/sumologic/sender.rb:105]: Or instead of "rethinking" it, I could just add a new parameter `stats_category` with default value of `Logstash.stats`.

Comment (astencel-sumo) [reply lib/logstash/outputs/sumologic/sender.rb:105]: Done
